version: "3"

services:
  server1:
    image: nginx
    volumes:
      - "./server1/:/var/www/html/"
      - "./conf/server.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
    networks:
      - cluster_net

  server2:
    image: nginx
    volumes:
      - "./server2/:/var/www/html/"
      - "./conf/server.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "8081:80"
    environment:
      - NGINX_PORT=80
    networks:
      - cluster_net

  server3:
    image: nginx
    volumes:
      - "./server3/:/var/www/html/"
      - "./conf/server.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "8082:80"
    environment:
      - NGINX_PORT=80
    networks:
      - cluster_net
    
  proxy:
    image: nginx
    volumes:
      - "./conf/proxy.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./certs/server/:/etc/nginx/certs/"
    ports:
      - "443:443"
    environment:
      - NGINX_PORT=443
    networks:
      - cluster_net

networks:
  cluster_net: